In [1]:
import numpy as np

## Arithmetic Operations

In [15]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
# size should be same 
# np.add(arr1,arr2)
arr1+arr2
np.subtract(arr1,arr2)
arr1-arr2
np.multiply(arr1,arr2)
arr1*arr2
np.divide(arr1,arr2)
arr1/arr2
np.floor_divide(arr2,arr1)
arr1//arr2
np.power(arr1,arr2)
arr1**arr2

array([  1,  32, 729])

## Broadcasting

In [17]:
l=[10,20,30,40,50]
arr=np.array(l)
arr

array([10, 20, 30, 40, 50])

In [18]:
# broadcasting - means we are performingsome operation on all elements 
arr+10

array([20, 30, 40, 50, 60])

In [19]:
arr*10

array([100, 200, 300, 400, 500])

In [20]:
arr=np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [21]:
arr+10

array([[11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40]])

## Deep and Shallow Copy 

In [61]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [62]:
# slice just creates the view of array so it reference to it 
slice=a[:10]
# this will make changes in original array
slice[0]=10

In [63]:
a

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [64]:
# this creates a copy so it will not affect the original array
# this will not make changes in original array
slice=slice*10
slice

array([100,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [65]:
slice[0]=2093
slice

array([2093,   20,   30,   40,   50,   60,   70,   80,   90,  100])

In [67]:
a

array([10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [68]:
b=np.arange(1,11)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
slice=b[:5]
slice

array([1, 2, 3, 4, 5])

In [71]:
# this will make changes in all sliced elements in original array as well 
slice[:]=slice*10
b

array([10, 20, 30, 40, 50,  6,  7,  8,  9, 10])

## Matrix Operations

In [72]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

In [77]:
# dot product in matrix 
a@b
# np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [74]:
a+b

array([[ 6,  8],
       [10, 12]])

In [78]:
# Transpose 
a.T

array([[1, 3],
       [2, 4]])

## Advanced Array operationsa

## Stacking

In [80]:
a
# stacking cannot be done on matrix it can be done only on vector

array([[1, 2],
       [3, 4]])

In [92]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [93]:
b=np.arange(5,9)
b

array([5, 6, 7, 8])

In [90]:
np.vstack((a,b))
# eke ke neeche ek 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [91]:
np.hstack((a,b))
# side by side just like normal concatenation in python list 

array([1, 2, 3, 4, 5, 6, 7, 8])

In [94]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [99]:
arr=np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [100]:
np.hsplit(arr,2)
# this divides matrix into equal halves horizontally

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [101]:
np.vsplit(arr,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]