## Indexing and slicing of vector

In [1]:
import numpy as np


In [2]:
arr=np.arange(11,20)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [4]:
# indexing
arr[6]


np.int64(17)

In [5]:
# slicing
arr[1:4]

array([12, 13, 14])

In [6]:
arr[:6:2]

array([11, 13, 15])

In [7]:
arr[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11])

In [9]:
arr[10:2:-1]

array([19, 18, 17, 16, 15, 14])

## Indexing and Slicing of Matrix

In [33]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
arr=arr.reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [35]:
arr[0]

array([1, 2, 3, 4, 5])

In [29]:
arr[0][4]

np.int64(5)

In [30]:
# row,col
arr[2,3]

np.int64(14)

In [37]:
# row slicing(start,end+1)  ,col slicing(start,end+1) 
arr[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [41]:
arr[0:,2]

array([ 3,  8, 13, 18])

In [43]:
arr[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

## Bool Indexing 


In [51]:
arr=np.arange(11,20)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [52]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False])

In [54]:
# True will give the actual value of A 
arr=arr[bool_index]
arr

IndexError: boolean index did not match indexed array along axis 0; size of axis is 4 but size of corresponding boolean axis is 9