In [58]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [4]:
#Get the shape of the matrix
data.shape

(5, 3)

In [12]:
#Find the average age of students
data.mean(0)[0]

np.float64(18.4)

In [16]:
#Extract Math marks of all students
math_result=data[:,1]
math_result

array([85, 92, 76, 65, 90])

In [28]:
#Find the highest Science mark
# data.max(axis=0)[2]
np.max(data[:,2])

np.int64(95)

In [19]:
#Get details of the student who scored more than 90 in Math
bool_index=math_result>90
bool_index

array([False,  True, False, False, False])

In [29]:
data[bool_index]

array([[19, 92, 88]])

In [30]:
#Increase Math marks of all students by 5.
data[:,1]=math_result+5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [32]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

3

In [34]:
x=np.mean(data,axis=0)
x[1:]

array([86.6, 83.2])

In [47]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>=80) & (data[:,2]>=80)]
# math=data[:,1]>=80
# math
# science=data[:,1]>=80
# science
# data

array([[19, 92, 88],
       [20, 90, 85]])

In [59]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])