In [ ]:
import numpy as np
# numpy array is faster than  list , contains homogenous elements 

Basic Array Creation 

In [3]:
#Basic array creation 

arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
a=[1,2,'hello']

In [5]:
arr1=np.array(a)
arr1
# if different type then it is converted to single type below is an example

array(['1', '2', 'hello'], dtype='<U21')

In [6]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
matrix=np.array(l)
matrix
# with numpy 2d matrix will look like it while in simple list it is not 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation Function

In [32]:
# arange(start,end+1,step)
# shift+tab can see the paramters of function 
arr=np.arange(1,11)
arr

arr2=np.arange(1,11,2)
arr2

array([1, 3, 5, 7, 9])

In [16]:
arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arr=np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
arr=np.linspace(1,50,5)
arr

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

Random Array generation 


In [23]:
np.random.rand(5)
# this will gave random numbers in array between 0 to 1 (NORMALIZATION)

array([0.56369845, 0.39724808, 0.5916443 , 0.46345582, 0.58157092])

In [24]:
np.random.randn(5)
# this will gave random numbers in array between -3 to 3 (STANDARDIZATION)

array([-0.38648109,  0.98636906,  0.23630102, -0.86232979,  1.55672923])

In [30]:
np.random.randint(10,20,5)

array([19, 17, 10, 18, 15], dtype=int32)

Array Attributes 


In [35]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr.size
# size returns total number of array 

9

In [38]:
arr.shape
# shape returns the no of rows and no of cols (tuple)

(3, 3)

In [40]:
arr.ndim

2

In [41]:
arr.dtype

dtype('int64')

Array Methods 


In [42]:
arr.min()

np.int64(1)

In [43]:
arr.max()

np.int64(9)

In [44]:
arr.sum()

np.int64(45)

In [46]:
np.sum(arr,axis=0)
# axis=0 col wise sum  and axis=1 then row wise sum 

array([12, 15, 18])

In [47]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [48]:
arr.mean()

np.float64(5.0)

In [49]:
arr.std()

np.float64(2.581988897471611)

In [50]:
arr.argmax()
# gives index of max value in array

np.int64(8)

In [52]:
arr.argmin()
# gives index of min value in array

np.int64(0)

Reshaping and resizing 


In [54]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [56]:
arr=arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])